/*
This is the demo version of the code. Since there were issues with the Gemini tokens,
we needed to manually upload the json files (though these were generated by using the prompt contained in App_with_ai.txs directly in the gemini chatbot). To see the code for the gemini API, look at App_with_ai.txs. 
*/
import * as React from "react";
import {
  PrimaryButton,
  DefaultButton,
  Text,
  Spinner,
  SpinnerSize,
  MessageBar,
  MessageBarType,
  Separator,
} from "@fluentui/react";
// (Gemini API key removed — using mock data from /data folder)

// ---------------------------------------------------------------------------
// Provinces — BC, ON, QC only
// ---------------------------------------------------------------------------
const PROVINCES = [
  { code: "ON", name: "Ontario" },
  { code: "QC", name: "Quebec" },
  { code: "BC", name: "British Columbia" },
];

// RAW_DATA & WORST_RANK_DATA placeholders (data now generated dynamically)
// ---------------------------------------------------------------------------
const EMPTY_DATA: any = { ON: { clauses: [] }, QC: { clauses: [] }, BC: { clauses: [] } };

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function computeProvinceScore(provinceCode: string, clauseStates: Record<string, string>, data: any) {
  const clauses = data[provinceCode]?.clauses || [];
  const active = clauses.filter((c: any) => clauseStates[c.id] !== "ignore");
  if (!active.length) return 0;
  const total = active.reduce((sum: number, c: any) =>
    sum + (clauseStates[c.id] === "limit" ? 0 : c.score), 0);
  return Math.round(total / active.length);
}

function barColor(score: number) {
  if (score >= 75) return "#1D9E75";
  if (score >= 55) return "#BA7517";
  return "#E24B4A";
}

// ---------------------------------------------------------------------------
// SummaryCards
// ---------------------------------------------------------------------------
function SummaryCards({ ranked, counts, totalClauses }: any) {
  const top = ranked[0];
  const avgAll = Math.round(ranked.reduce((s: number, r: any) => s + r.score, 0) / ranked.length);
  const cards = [
    { val: top.province.name, label: "Best Forum" },
    { val: top.score, label: "Top score / 100" },
    { val: `${counts.evaluate} / ${totalClauses}`, label: "Clauses evaluated" },
    { val: avgAll, label: "Average score" },
  ];
  return (
    <div style={{ display: "flex", gap: 12, marginBottom: "1.5rem" }}>
      {cards.map((c) => (
        <div key={c.label} style={{
          flex: 1, background: "var(--color-background-secondary)",
          borderRadius: "var(--border-radius-md)", padding: "10px 14px",
        }}>
          <div style={{ fontSize: 18, fontWeight: 500, color: "var(--color-text-primary)" }}>{c.val}</div>
          <div style={{ fontSize: 11, color: "var(--color-text-tertiary)", marginTop: 2 }}>{c.label}</div>
        </div>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// ProvinceClausePanel — worst-ranked clauses with "Better in X" badge
// ---------------------------------------------------------------------------
const PROVINCE_NAMES_MAP: Record<string, string> = { ON: "Ontario", QC: "Quebec", BC: "British Columbia" };

function ProvinceClausePanel({ worstClauses, clauseStates, clauseText, open }: any) {
  const visible = worstClauses.filter((c: any) => clauseStates[c.id] !== "ignore");

  return (
    <div style={{
      borderTop: open ? "0.5px solid var(--color-border-tertiary)" : "none",
      maxHeight: open ? 900 : 0, overflow: "hidden",
      transition: "max-height 0.3s ease",
      padding: open ? "12px 16px 16px" : "0 16px",
    }}>
      {open && visible.length > 0 && (
        <div style={{
          display: "flex", alignItems: "center", gap: 6, marginBottom: 10,
          fontSize: 11, fontWeight: 500, color: "#BA7517",
          textTransform: "uppercase", letterSpacing: "0.07em",
        }}>
          <span style={{ fontSize: 14 }}>⚠</span>
          Clauses to watch in this jurisdiction
        </div>
      )}

      {visible.map((c: any) => {
        const state = clauseStates[c.id];
        const isLimit = state === "limit";
        const betterProvinceName = PROVINCE_NAMES_MAP[c.betterIn] ?? c.betterIn;

        return (
          <div key={c.id} style={{
            padding: "10px 12px", borderRadius: "var(--border-radius-md)",
            border: "0.5px solid #E8A040",
            marginBottom: 8,
            background: "#FFFBF2",
            opacity: isLimit ? 0.6 : 1, transition: "opacity 0.2s",
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 5, flexWrap: "wrap" }}>
              <span style={{ fontSize: 11, fontWeight: 500, fontFamily: "var(--font-mono)", color: "var(--color-text-tertiary)" }}>
                {c.id}
              </span>
              {isLimit && (
                <span style={{ fontSize: 11, padding: "1px 6px", borderRadius: 20, background: "#FCEBEB", color: "#791F1F" }}>
                  limited
                </span>
              )}
              <span style={{ fontSize: 11, padding: "2px 8px", borderRadius: 20, background: "#FAEEDA", color: "#633806" }}>
                {isLimit ? "0 / 100" : `${c.score} / 100`}
              </span>
              <span style={{
                marginLeft: "auto",
                fontSize: 11, padding: "2px 9px", borderRadius: 20,
                background: "#EAF3DE", color: "#27500A",
                fontWeight: 500, whiteSpace: "nowrap",
              }}>
                Better in {betterProvinceName}
              </span>
            </div>
            <p style={{
              fontSize: 13, color: "var(--color-text-secondary)", lineHeight: 1.5,
              margin: "0 0 6px", textDecoration: isLimit ? "line-through" : "none",
            }}>
              {clauseText[c.id] ?? c.id}
            </p>
            <div style={{
              fontSize: 12, color: "var(--color-text-tertiary)",
              borderLeft: "2px solid #E8A040", paddingLeft: 8,
            }}>
              {c.notes}
            </div>
          </div>
        );
      })}

      {visible.length === 0 && open && (
        <p style={{ fontSize: 13, color: "var(--color-text-tertiary)", margin: 0 }}>
          No clause warnings for this province.
        </p>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// ProvinceRow
// ---------------------------------------------------------------------------
function ProvinceRow({ province, rank, score, worstClauses, clauseStates, clauseText, open, onToggle }: any) {
  const rankStyle =
    rank === 0 ? { background: "#FAEEDA", color: "#633806" }
      : rank === 1 ? { background: "#D3D1C7", color: "#2C2C2A" }
        : rank === 2 ? { background: "#F5C4B3", color: "#4A1B0C" }
          : { background: "var(--color-background-secondary)", color: "var(--color-text-secondary)" };

  return (
    <div style={{
      border: "0.5px solid var(--color-border-tertiary)",
      borderRadius: "var(--border-radius-lg)",
      background: "var(--color-background-primary)", overflow: "hidden",
    }}>
      <div onClick={onToggle} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", cursor: "pointer" }}>
        <span style={{
          width: 22, height: 22, borderRadius: "50%",
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: 11, fontWeight: 500, flexShrink: 0, ...rankStyle,
        }}>{rank + 1}</span>
        <span style={{ fontSize: 14, fontWeight: 500, color: "var(--color-text-primary)", flex: 1 }}>
          {province.name}
        </span>
        <div style={{ flex: 1, maxWidth: 140, height: 4, background: "var(--color-background-tertiary)", borderRadius: 2, overflow: "hidden" }}>
          <div style={{ width: `${score}%`, height: "100%", background: barColor(score), borderRadius: 2, transition: "width 0.4s ease" }} />
        </div>
        <span style={{ fontSize: 13, fontWeight: 500, minWidth: 32, textAlign: "right", color: barColor(score) }}>
          {score}
        </span>
        <span style={{
          fontSize: 18, color: "var(--color-text-tertiary)", marginLeft: 4,
          display: "inline-block", transition: "transform 0.2s",
          transform: open ? "rotate(90deg)" : "rotate(0deg)",
        }}>›</span>
      </div>
      <ProvinceClausePanel
        worstClauses={worstClauses}
        clauseStates={clauseStates}
        clauseText={clauseText}
        open={open}
      />
    </div>
  );
}

// ---------------------------------------------------------------------------
// ProvinceRanking Main Export
// ---------------------------------------------------------------------------
export function ProvinceRanking({
  clauseStates,
  clauseText,
  data = EMPTY_DATA,
  worstData = EMPTY_DATA,
}: any) {
  const [openProvince, setOpenProvince] = React.useState<string | null>(null);

  const ranked = React.useMemo(() =>
    PROVINCES.map((p) => ({
      province: p,
      score: computeProvinceScore(p.code, clauseStates, data),
      worstClauses: worstData[p.code]?.clauses ?? [],
    })).sort((a, b) => b.score - a.score),
    [clauseStates, data, worstData]);

  return (
    <div style={{ fontFamily: "var(--font-sans, sans-serif)", padding: "1.5rem 0" }}>
      <p style={{
        fontSize: 11, fontWeight: 500, letterSpacing: "0.08em",
        textTransform: "uppercase", color: "var(--color-text-tertiary)", margin: "0 0 10px",
      }}>
        Province ranking
      </p>
      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        {ranked.map(({ province, score, worstClauses }, i) => (
          <ProvinceRow
            key={province.code}
            province={province}
            rank={i}
            score={score}
            worstClauses={worstClauses}
            clauseStates={clauseStates}
            clauseText={clauseText}
            open={openProvince === province.code}
            onToggle={() => setOpenProvince((prev) => prev === province.code ? null : province.code)}
          />
        ))}
      </div>
    </div>
  );
}

/**
 * Global forums dictionary — mirrors mai_civil_coders.py `forums`.
 * Scores accumulate across all clauses: +score when enforce=true, -score when enforce=false.
 */
const FORUMS_INIT: Record<string, number> = {
  "British Columbia": 0,
  "Ontario": 0,
  "Quebec": 0,
};

// ---------------------------------------------------------------------------
// Clause triage states (mirrors teammate's pattern)
//   "default" — sent to Gemini, scored as-is
//   "limit"   — sent to Gemini but score → 0 (user wants to minimise enforceability)
//   "ignore"  — excluded from Gemini loop entirely
// ---------------------------------------------------------------------------
const S = { DEFAULT: "default", LIMIT: "limit", IGNORE: "ignore" } as const;
type ClauseState = typeof S[keyof typeof S];

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AppProps {
  title: string;
}

/** Enforceability bucket per clause, keyed by score 0|1|2. Mirrors clause.forums in Python. */
type ClauseForums = { 0: Set<string>; 1: Set<string>; 2: Set<string> };

/** A single clause node in the document hierarchy. */
interface ClauseNode {
  id: string;
  fullText: string;
  /** First 5 words, used as the display label. */
  shortTitle: string;
  /** 0 = top-level (e.g. "1."), 1 = sub (e.g. "1.1"), 2 = sub-sub (e.g. "1.1.1") */
  level: number;
  /** The numbering prefix extracted from the paragraph, e.g. "1.", "1.1", "2.3.1" */
  numbering: string;
  parentId: string | null;
  childIds: string[];
  /** Human-readable name (= shortTitle). Maps to ClauseNode.name in Python. */
  name: string;
  /**
   * enforce=true  → user wants this clause enforced (DEFAULT state).
   * enforce=false → user wants to limit enforceability (LIMIT state).
   * Mirrors ClauseNode.enforce in Python.
   */
  enforce: boolean;
  /** Per-clause jurisdiction buckets populated after Gemini analysis. */
  forums: ClauseForums;
}

/** Shape of one jurisdiction entry returned by the mock data files. */
interface GeminiJurisdiction {
  province: string;
  enforceability_score: number;
  legal_sources: string[];
  exceptions: string[];
}

/** Full mock response for a single clause. */
interface GeminiClauseResponse {
  clause_id: string;
  jurisdictions: GeminiJurisdiction[];
}

// ---------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------

/** Detect whether a paragraph is a numbered heading and return its level + numbering prefix. */
function detectHeading(text: string): { level: number; numbering: string } | null {
  // Level 2 — e.g. "1.1.1 Some text"
  let m = text.match(/^(\d+\.\d+\.\d+)[\s.]/);
  if (m) return { level: 2, numbering: m[1] };

  // Level 1 — e.g. "1.1 Some text" (not followed by another .digit so we don't grab 1.1.1)
  m = text.match(/^(\d+\.\d+)(?!\.\d)[\s.]/);
  if (m) return { level: 1, numbering: m[1] };

  // Level 0 — e.g. "1. Some text"
  m = text.match(/^(\d+)\.\s/);
  if (m) return { level: 0, numbering: m[1] + "." };

  return null;
}

/** Truncate text to at most `n` words. */
function firstWords(text: string, n = 5): string {
  return text.split(/\s+/).slice(0, n).join(" ");
}

/**
 * Build a flat list of ClauseNodes from raw paragraph strings.
 * Parent–child relationships are determined by heading level transitions.
 */
function buildClauseTree(paragraphTexts: string[]): ClauseNode[] {
  const nodes: ClauseNode[] = [];
  const byId = new Map<string, ClauseNode>();
  const lastAtLevel = new Map<number, ClauseNode>();

  let serial = 0;
  for (const text of paragraphTexts) {
    if (!text.trim()) continue;
    const detected = detectHeading(text);
    if (!detected) continue;

    const { level, numbering } = detected;
    const id = `clause_${serial++}`;

    let parentId: string | null = null;
    if (level > 0) {
      const parent = lastAtLevel.get(level - 1);
      if (parent) parentId = parent.id;
    }

    const node: ClauseNode = {
      id,
      fullText: text,
      shortTitle: firstWords(text, 5),
      level,
      numbering,
      parentId,
      childIds: [],
      name: firstWords(text, 5),
      enforce: true,           // default; updated when user sets LIMIT state
      forums: { 0: new Set(), 1: new Set(), 2: new Set() },
    };

    nodes.push(node);
    byId.set(id, node);
    lastAtLevel.set(level, node);

    // Use Array.from() instead of for...of on Map — required for ES5 targets.
    Array.from(lastAtLevel.keys()).forEach((l) => {
      if (l > level) lastAtLevel.delete(l);
    });

    if (parentId) {
      byId.get(parentId)?.childIds.push(id);
    }
  }

  return nodes;
}

/** Recursively collect all descendant IDs of a node. */
function collectDescendants(nodeId: string, byId: Map<string, ClauseNode>): string[] {
  const node = byId.get(nodeId);
  if (!node || node.childIds.length === 0) return [];
  const result: string[] = [...node.childIds];
  for (const childId of node.childIds) {
    result.push(...collectDescendants(childId, byId));
  }
  return result;
}

// ---------------------------------------------------------------------------
// Mock data loader — loads pre-saved JSON files from /data
// ---------------------------------------------------------------------------

/** Simple promise-based delay. */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Load all numbered JSON files from /data at build time.
 * Keys are 1-based integers matching the clause sequential number.
 * e.g. clause_0 → 1.json, clause_1 → 2.json, etc.
 */
const NUMBERED_DATA: Record<number, GeminiClauseResponse> = (() => {
  const ctx = (require as any).context("../../data", false, /^\.\/(\d+)\.json$/);
  const map: Record<number, GeminiClauseResponse> = {};
  ctx.keys().forEach((key: string) => {
    const match = key.match(/^\.(\/(\d+))\.json$/);
    if (match) map[parseInt(match[2])] = ctx(key) as GeminiClauseResponse;
  });
  return map;
})();

// ---------------------------------------------------------------------------
// UI helpers — mirroring teammate's style
// ---------------------------------------------------------------------------

/** Derive the "dominant" triage state of a parent node from its children's states. */
function parentState(childIds: string[], clauseStates: Record<string, ClauseState>): ClauseState {
  const states = childIds.map((id) => clauseStates[id]);
  if (states.every((s) => s === S.IGNORE)) return S.IGNORE;
  if (states.every((s) => s === S.LIMIT)) return S.LIMIT;
  return S.DEFAULT;
}

/** True when a parent has a mix of states among its children. */
function isMixedState(childIds: string[], clauseStates: Record<string, ClauseState>): boolean {
  const states = childIds.map((id) => clauseStates[id]);
  return states.some((s) => s !== S.DEFAULT) && !states.every((s) => s === states[0]);
}

/** Returns the first 5 words of a clause as a short display label. */
function smartTruncate(text: string, maxWords = 5): string {
  return text.split(/\s+/).slice(0, maxWords).join(" ");
}

// ---------------------------------------------------------------------------
// IconButton — small circular triage button (Limit / Ignore)
// ---------------------------------------------------------------------------

interface IconButtonProps {
  active: boolean;
  activeColor: string;
  activeBg: string;
  label: string;
  onClick: () => void;
  children: React.ReactNode;
}

const IconButton: React.FC<IconButtonProps> = ({ active, activeColor, activeBg, label, onClick, children }) => (
  <button
    aria-label={label}
    onClick={(e) => { e.stopPropagation(); onClick(); }}
    style={{
      width: 26, height: 26, borderRadius: "50%",
      border: active ? `1.5px solid ${activeColor}` : "0.5px solid #c8c6c4",
      background: active ? activeBg : "transparent",
      color: active ? activeColor : "#a19f9d",
      fontSize: 12, fontWeight: 700,
      cursor: "pointer",
      display: "flex", alignItems: "center", justifyContent: "center",
      flexShrink: 0,
      transition: "background 0.15s, border-color 0.15s, color 0.15s",
      padding: 0,
    }}
  >
    {children}
  </button>
);

// ---------------------------------------------------------------------------
// ClauseRow — leaf clause (level > 0) with Limit / Ignore buttons
// ---------------------------------------------------------------------------

interface ClauseRowProps {
  node: ClauseNode;
  state: ClauseState;
  onSetState: (id: string, state: ClauseState) => void;
  onNavigate: (node: ClauseNode) => void;
}

const ClauseRow: React.FC<ClauseRowProps> = ({ node, state, onSetState, onNavigate }) => {
  const isLimit = state === S.LIMIT;
  const isIgnore = state === S.IGNORE;
  const label = smartTruncate(node.fullText);

  return (
    <div
      onClick={() => onNavigate(node)}
      title={node.fullText}
      style={{
        display: "flex", alignItems: "flex-start", gap: 10,
        padding: "7px 10px 7px 32px",
        borderRadius: 6,
        border: isLimit
          ? "1px solid #E24B4A"
          : isIgnore
            ? "0.5px dashed #c8c6c4"
            : "0.5px solid #edebe9",
        background: isLimit ? "#FFF5F5" : isIgnore ? "#f3f2f1" : "#ffffff",
        opacity: isIgnore ? 0.5 : 1,
        transition: "border-color 0.15s, background 0.15s, opacity 0.15s",
        position: "relative",
        cursor: "pointer",
      }}>
      {/* Indent connector — vertical line */}
      <div style={{
        position: "absolute", left: 14, top: 0, bottom: 0,
        width: 1, background: "#edebe9",
      }} />
      {/* Indent connector — horizontal stub */}
      <div style={{
        position: "absolute", left: 14, top: "50%",
        width: 10, height: 1, background: "#edebe9",
      }} />

      <div style={{ flex: 1, minWidth: 0 }}>
        <span style={{
          fontSize: 11, fontWeight: 500, fontFamily: "monospace",
          color: "#a19f9d", marginRight: 8,
        }}>
          {node.numbering}
        </span>
        <span style={{
          fontSize: 13, lineHeight: 1.5,
          color: isIgnore ? "#a19f9d" : "#323130",
          textDecoration: isIgnore ? "line-through" : "none",
        }}>
          {label}…
        </span>
      </div>

      <div style={{ display: "flex", gap: 5, flexShrink: 0, alignItems: "center" }}>
        <IconButton
          active={isLimit}
          activeColor="#A32D2D"
          activeBg="#FCEBEB"
          label="Limit enforceability"
          onClick={() => onSetState(node.id, isLimit ? S.DEFAULT : S.LIMIT)}
        >!</IconButton>
        <IconButton
          active={isIgnore}
          activeColor="#605e5c"
          activeBg="#f3f2f1"
          label="Ignore clause"
          onClick={() => onSetState(node.id, isIgnore ? S.DEFAULT : S.IGNORE)}
        >✕</IconButton>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// SectionRow — collapsible group header with cascade Limit / Ignore buttons
// ---------------------------------------------------------------------------

interface SectionRowProps {
  node: ClauseNode;          // level-0 node
  children: ClauseNode[];    // its direct children
  clauseStates: Record<string, ClauseState>;
  onSetState: (id: string, state: ClauseState) => void;
  onCascade: (parentId: string, state: ClauseState) => void;
  onNavigate: (node: ClauseNode) => void;
}

const SectionRow: React.FC<SectionRowProps> = ({ node, children, clauseStates, onSetState, onCascade, onNavigate }) => {
  const [open, setOpen] = React.useState(true);

  const domState = children.length > 0 ? parentState(children.map((c) => c.id), clauseStates) : clauseStates[node.id];
  const isLimit = domState === S.LIMIT;
  const isIgnore = domState === S.IGNORE;
  const mixed = children.length > 0 && isMixedState(children.map((c) => c.id), clauseStates);

  // For leaf-level-0 nodes (no children), fall back to ClauseRow behaviour
  if (children.length === 0) {
    return <ClauseRow node={node} state={clauseStates[node.id]} onSetState={onSetState} onNavigate={onNavigate} />;
  }

  return (
    <div style={{ marginBottom: 6 }}>
      {/* Section header */}
      <div
        onClick={() => setOpen((o) => !o)}
        style={{
          display: "flex", alignItems: "center", gap: 10,
          padding: "8px 12px",
          borderRadius: 6,
          background: "#f3f2f1",
          border: isLimit
            ? "1px solid #E24B4A"
            : isIgnore
              ? "0.5px dashed #c8c6c4"
              : "0.5px solid #c8c6c4",
          cursor: "pointer",
          userSelect: "none",
        }}
      >
        {/* Chevron */}
        <span style={{
          fontSize: 11, color: "#a19f9d",
          display: "inline-block", transition: "transform 0.2s",
          transform: open ? "rotate(90deg)" : "rotate(0deg)",
          flexShrink: 0,
        }}>▶</span>

        {/* Numbering */}
        <span style={{ fontSize: 11, fontWeight: 500, fontFamily: "monospace", color: "#a19f9d", flexShrink: 0 }}>
          §{node.numbering.replace(".", "")}
        </span>

        {/* Title */}
        <span style={{ fontSize: 14, fontWeight: 500, color: "#323130", flex: 1 }}>
          {node.shortTitle}{node.shortTitle !== node.fullText && "…"}
        </span>

        {/* Mixed badge */}
        {mixed && (
          <span style={{ fontSize: 11, padding: "1px 7px", borderRadius: 20, background: "#FAEEDA", color: "#633806", flexShrink: 0 }}>
            mixed
          </span>
        )}

        {/* Child count */}
        <span style={{ fontSize: 11, color: "#a19f9d", flexShrink: 0 }}>
          {children.length} clause{children.length !== 1 ? "s" : ""}
        </span>

        {/* Cascade buttons */}
        <div style={{ display: "flex", gap: 5, flexShrink: 0 }}>
          <IconButton
            active={isLimit}
            activeColor="#A32D2D"
            activeBg="#FCEBEB"
            label="Limit all clauses in section"
            onClick={() => onCascade(node.id, isLimit ? S.DEFAULT : S.LIMIT)}
          >!</IconButton>
          <IconButton
            active={isIgnore}
            activeColor="#605e5c"
            activeBg="#f3f2f1"
            label="Ignore all clauses in section"
            onClick={() => onCascade(node.id, isIgnore ? S.DEFAULT : S.IGNORE)}
          >✕</IconButton>
        </div>
      </div>

      {/* Child clauses */}
      {open && (
        <div style={{ display: "flex", flexDirection: "column", gap: 4, marginTop: 4, paddingLeft: 8 }}>
          {children.map((child) => (
            <ClauseRow
              key={child.id}
              node={child}
              state={clauseStates[child.id]}
              onSetState={onSetState}
              onNavigate={onNavigate}
            />
          ))}
        </div>
      )}
    </div>
  );
};

// ---------------------------------------------------------------------------
// LandingPage component — FORA Start Panel (Stitch design)
// ---------------------------------------------------------------------------

interface LandingPageProps {
  onRecommendDisputeForum: () => void;
}

const LandingPage: React.FC<LandingPageProps> = ({ onRecommendDisputeForum }) => {
  const menuItems: Array<{ icon: string; label: string; onClick?: () => void; dividerAfter?: boolean }> = [
    { icon: "📄", label: "Compare documents" },
    { icon: "✂️", label: "Summarize redlines" },
    { icon: "📊", label: "Benchmarks" },
    { icon: "📖", label: "Definitions" },
    { icon: "⚖️", label: "Recommend dispute forum", onClick: onRecommendDisputeForum, dividerAfter: true },
    { icon: "📝", label: "Draft new document" },
    { icon: "✏️", label: "Revise document" },
  ];

  return (
    <div style={{
      display: "flex", flexDirection: "column", height: "100vh",
      fontFamily: "'Segoe UI', sans-serif",
      background: "#F3F3F3",
      maxWidth: "420px",
    }}>
      {/* Header */}
      <div style={{
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "14px 16px",
        background: "#FFFFFF",
        borderBottom: "1px solid #E0E0E0",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ fontSize: 20 }}>🏛️</span>
          <span style={{ fontSize: 16, fontWeight: 700, color: "#1a1a1a", letterSpacing: "0.04em" }}>FORA</span>
        </div>
        <button style={{
          background: "none", border: "none", cursor: "pointer",
          fontSize: 20, color: "#555", padding: 4, borderRadius: 6,
          display: "flex", alignItems: "center",
        }} title="Settings">
          ⚙️
        </button>
      </div>

      {/* Tab bar */}
      <div style={{
        display: "flex", gap: 8, padding: "12px 16px 8px",
        background: "#FFFFFF",
        borderBottom: "1px solid #E8E8E8",
      }}>
        {["Ask", "Review", "Draft"].map((tab) => (
          <button
            key={tab}
            style={{
              padding: "6px 16px",
              border: "1.5px solid #C8C8C8",
              borderRadius: 20,
              background: "#FFFFFF",
              color: "#1a1a1a",
              fontSize: 13,
              fontWeight: 500,
              cursor: "pointer",
              transition: "background 0.15s",
            }}
          >
            {tab}
          </button>
        ))}
        <button style={{
          marginLeft: "auto",
          padding: "6px 10px",
          border: "1.5px solid #C8C8C8",
          borderRadius: 20,
          background: "#FFFFFF",
          color: "#555",
          fontSize: 13,
          cursor: "pointer",
        }}>▾</button>
      </div>

      {/* Menu list */}
      <div style={{ flex: 1, padding: "0 0 80px" }}>
        <p style={{
          fontSize: 11, fontWeight: 600, color: "#888",
          padding: "14px 20px 6px",
          letterSpacing: "0.08em",
          textTransform: "uppercase",
          margin: 0,
        }}>More Spells</p>

        {menuItems.map(({ icon, label, onClick, dividerAfter }) => (
          <React.Fragment key={label}>
            <button
              onClick={onClick}
              style={{
                width: "100%",
                display: "flex",
                alignItems: "center",
                gap: 14,
                padding: "14px 20px",
                background: onClick ? "#FFFFFF" : "transparent",
                border: "none",
                borderBottom: "none",
                cursor: onClick ? "pointer" : "default",
                textAlign: "left",
                fontSize: 14,
                color: onClick ? "#1a1a1a" : "#555",
                fontWeight: onClick ? 500 : 400,
                transition: "background 0.15s",
              }}
              onMouseEnter={(e) => { if (onClick) (e.currentTarget as HTMLButtonElement).style.background = "#EAEAEA"; }}
              onMouseLeave={(e) => { if (onClick) (e.currentTarget as HTMLButtonElement).style.background = "#FFFFFF"; }}
            >
              <span style={{ fontSize: 18, width: 24, textAlign: "center", flexShrink: 0 }}>{icon}</span>
              <span>{label}</span>
            </button>
            {dividerAfter && <hr style={{ border: "none", borderTop: "1px solid #DCDCDC", margin: "0 20px" }} />}
          </React.Fragment>
        ))}
      </div>

      {/* Bottom navigation */}
      <div style={{
        position: "fixed", bottom: 0, left: 0, right: 0, maxWidth: 420,
        display: "flex",
        borderTop: "1px solid #DCDCDC",
        background: "#FFFFFF",
        padding: "8px 0 4px",
      }}>
        {[
          { icon: "📊", label: "ANALYSIS" },
          { icon: "📚", label: "LIBRARY" },
          { icon: "🕐", label: "HISTORY" },
        ].map(({ icon, label }, i) => (
          <button
            key={label}
            style={{
              flex: 1,
              display: "flex", flexDirection: "column", alignItems: "center",
              gap: 2, padding: "6px 0",
              background: "none", border: "none", cursor: "pointer",
              borderTop: i === 0 ? "2px solid #1a1a1a" : "2px solid transparent",
            }}
          >
            <span style={{ fontSize: 18 }}>{icon}</span>
            <span style={{ fontSize: 10, fontWeight: 600, color: i === 0 ? "#1a1a1a" : "#999", letterSpacing: "0.06em" }}>{label}</span>
          </button>
        ))}
      </div>

      {/* Help button */}
      <button style={{
        position: "fixed", bottom: 70, right: 16,
        width: 40, height: 40, borderRadius: "50%",
        background: "#FFFFFF",
        border: "1.5px solid #DCDCDC",
        cursor: "pointer",
        fontSize: 18,
        display: "flex", alignItems: "center", justifyContent: "center",
        boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
      }} title="Help">
        ❓
      </button>
    </div>
  );
};

// ---------------------------------------------------------------------------
// App component
// ---------------------------------------------------------------------------

const App: React.FC<AppProps> = (_props) => {
  const [showLanding, setShowLanding] = React.useState(true);
  const [clauses, setClauses] = React.useState<ClauseNode[]>([]);
  const [clauseStates, setClauseStates] = React.useState<Record<string, ClauseState>>({});
  const [started, setStarted] = React.useState(false);
  const [rankingData, setRankingData] = React.useState<any>(EMPTY_DATA);
  const [worstData, setWorstData] = React.useState<any>(EMPTY_DATA);
  const [isRunning, setIsRunning] = React.useState(false);
  const [statusMessage, setStatusMessage] = React.useState<string | null>(null);
  const [errorMessage, setErrorMessage] = React.useState<string | null>(null);
  /** Whether to show the results panel. */
  const [showResults, setShowResults] = React.useState(false);
  /** Best jurisdiction name from scoring. */
  const [bestJurisdiction, setBestJurisdiction] = React.useState<string | null>(null);

  /** Derived map for fast lookup. */
  const clauseById = React.useMemo<Map<string, ClauseNode>>(() => {
    const m = new Map<string, ClauseNode>();
    clauses.forEach((c) => m.set(c.id, c));
    return m;
  }, [clauses]);

  /** clauseText map required by ProvinceRanking: { clauseId: fullText } */
  const clauseText = React.useMemo<Record<string, string>>(() => {
    const m: Record<string, string> = {};
    clauses.forEach((c) => { m[c.id] = c.fullText; });
    return m;
  }, [clauses]);

  /** All level-0 (top-level) nodes — section headers. */
  const sections = React.useMemo(() => clauses.filter((c) => c.level === 0), [clauses]);

  // -------------------------------------------------------------------------
  // START — read paragraphs from Word, build hierarchy in React state.
  //         Nothing is written to the document.
  // -------------------------------------------------------------------------
  const handleStart = async () => {
    setIsRunning(true);
    setStatusMessage(null);
    setErrorMessage(null);

    try {
      const texts: string[] = [];

      await Word.run(async (context) => {
        const paragraphs = context.document.body.paragraphs;
        paragraphs.load("items/text");
        await context.sync();
        paragraphs.items.forEach((p) => texts.push(p.text));
      });

      const tree = buildClauseTree(texts);

      if (tree.length === 0) {
        setErrorMessage(
          "No numbered headings found. Make sure the document uses numbered clauses like '1. Definitions' or '1.1 Services'."
        );
        return;
      }

      // Initialise all clauses to DEFAULT state
      const initialStates: Record<string, ClauseState> = {};
      tree.forEach((c) => { initialStates[c.id] = S.DEFAULT; });

      setClauses(tree);
      setClauseStates(initialStates);
      setStarted(true);
      setStatusMessage(`Found ${tree.length} clause(s). Triage them below, then click Continue.`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      setErrorMessage(`Start failed: ${msg}`);
    } finally {
      setIsRunning(false);
    }
  };

  // -------------------------------------------------------------------------
  // Triage handlers
  // -------------------------------------------------------------------------

  /** Set a single clause's state. */
  const handleSetState = React.useCallback((id: string, state: ClauseState) => {
    setClauseStates((prev) => ({ ...prev, [id]: state }));
  }, []);

  /**
   * Cascade a state to all children of a parent node.
   * Also sets the parent itself.
   */
  const handleCascade = React.useCallback((parentId: string, targetState: ClauseState) => {
    const descendants = collectDescendants(parentId, clauseById);
    setClauseStates((prev) => {
      const next = { ...prev, [parentId]: targetState };
      descendants.forEach((id) => { next[id] = targetState; });
      return next;
    });
  }, [clauseById]);

  /**
   * Navigate to the clause's paragraph in the Word document.
   * Uses body.search() with the first ~60 characters to locate it, then selects it.
   */
  const handleNavigate = React.useCallback(async (node: ClauseNode) => {
    try {
      // Use a generous prefix of the clause text as the search target.
      const searchText = node.fullText.slice(0, 60).trim();
      await Word.run(async (context) => {
        const results = context.document.body.search(searchText, { matchCase: false, matchWholeWord: false });
        results.load("items");
        await context.sync();
        if (results.items.length > 0) {
          results.items[0].select();
          await context.sync();
        }
      });
    } catch {
      // Navigation is best-effort; silently ignore if it fails.
    }
  }, []);

  const handleReset = () => {
    // Reset all clauses to DEFAULT — keep the list open.
    const next: Record<string, ClauseState> = {};
    clauses.forEach((c) => { next[c.id] = S.DEFAULT; });
    setClauseStates(next);
    setStatusMessage(null);
    setErrorMessage(null);
    setShowResults(false);
    setBestJurisdiction(null);
    setRankingData(EMPTY_DATA);
    setWorstData(EMPTY_DATA);
  };

  /** Set every clause to IGNORE. */
  const handleIgnoreAll = () => {
    const next: Record<string, ClauseState> = {};
    clauses.forEach((c) => { next[c.id] = S.IGNORE; });
    setClauseStates(next);
    setStatusMessage(`✕ All ${clauses.length} clause(s) set to Ignore.`);
  };

  /** Set every clause to LIMIT. */
  const handleLimitAll = () => {
    const next: Record<string, ClauseState> = {};
    clauses.forEach((c) => { next[c.id] = S.LIMIT; });
    setClauseStates(next);
    setStatusMessage(`! All ${clauses.length} clause(s) set to Limit.`);
  };

  // -------------------------------------------------------------------------
  // CONTINUE — mock: 2-second delay, load pre-saved JSON data, run scoring.
  // -------------------------------------------------------------------------
  const handleContinue = async () => {
    const active = clauses.filter((c) => clauseStates[c.id] !== S.IGNORE);
    if (active.length === 0) {
      setStatusMessage("⚠️ All clauses are ignored. Un-ignore at least one to continue.");
      return;
    }

    setIsRunning(true);
    setShowResults(false);
    setStatusMessage(null);
    setErrorMessage(null);

    try {
      // Simulate analysis time
      await sleep(2000);

      // Run processClauseResults scoring (same logic as Python).
      // Each clause is matched to its numbered JSON file (1-based: clause_0 → 1.json).
      // Clauses without a corresponding JSON file are silently skipped.
      const forums: Record<string, number> = { ...FORUMS_INIT };

      const dynamicData: any = { ON: { clauses: [] }, QC: { clauses: [] }, BC: { clauses: [] } };

      active.forEach((clauseNode) => {
        // Derive the 1-based clause number from the internal id ("clause_0" → 1)
        const clauseNumber = parseInt(clauseNode.id.replace("clause_", "")) + 1;
        const response = NUMBERED_DATA[clauseNumber];
        if (!response) return; // no JSON file for this clause — skip

        clauseNode.enforce = clauseStates[clauseNode.id] !== S.LIMIT;
        clauseNode.forums = { 0: new Set(), 1: new Set(), 2: new Set() };

        for (const entry of response.jurisdictions ?? []) {
          const fName = entry.province;
          const score = Math.max(0, Math.min(2, Math.round(entry.enforceability_score))) as 0 | 1 | 2;

          const pCode = fName === "Ontario" ? "ON" : fName === "Quebec" ? "QC" : fName === "British Columbia" ? "BC" : null;
          if (pCode) {
            const percentScore = score === 2 ? 90 : score === 1 ? 65 : 30;
            const notes = (entry.legal_sources?.[0] ?? "");
            dynamicData[pCode].clauses.push({
              id: clauseNode.id,
              score: percentScore,
              notes: notes
            });
          }

          clauseNode.forums[score].add(fName);
          if (fName in forums) {
            forums[fName] += clauseNode.enforce ? score : -score;
          }
        }
      });

      setRankingData(dynamicData);

      // best_j = province with highest aggregate score
      const best_j = Object.keys(forums).reduce((a, b2) => forums[a] >= forums[b2] ? a : b2);

      // Per-province flag_clauses: clauses where that province is NOT in forums[2]
      // For each flagged clause, find which province scored best (betterIn)
      const PCODE_TO_NAME: Record<string, string> = { ON: "Ontario", QC: "Quebec", BC: "British Columbia" };

      const computedWorstData: any = { ON: { clauses: [] }, QC: { clauses: [] }, BC: { clauses: [] } };

      for (const pCode of ["ON", "QC", "BC"]) {
        const pName = PCODE_TO_NAME[pCode];
        const flagged = active.filter((c) => !c.forums[2].has(pName));

        flagged.forEach((c) => {
          // Find the province that scored highest for this clause in dynamicData
          let bestCode: string | null = null;
          let bestScore = -1;
          for (const otherCode of ["ON", "QC", "BC"]) {
            if (otherCode === pCode) continue;
            const entry = dynamicData[otherCode].clauses.find((x: any) => x.id === c.id);
            if (entry && entry.score > bestScore) {
              bestScore = entry.score;
              bestCode = otherCode;
            }
          }

          // Get this clause's score and notes for this province
          const thisEntry = dynamicData[pCode].clauses.find((x: any) => x.id === c.id);
          if (!thisEntry) return;

          computedWorstData[pCode].clauses.push({
            id: c.id,
            score: thisEntry.score,
            notes: thisEntry.notes,
            betterIn: bestCode ?? "",
          });
        });
      }

      setWorstData(computedWorstData);

      console.log("=== Fora — NUMBERED_DATA keys:", Object.keys(NUMBERED_DATA).join(", "));
      console.log("=== Best jurisdiction:", best_j, "| Scores:", forums);

      setBestJurisdiction(best_j);
      setShowResults(true);
      setStatusMessage(`✅ Analysis complete. Best jurisdiction: ${best_j}.`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      setErrorMessage(`Continue failed: ${msg}`);
    } finally {
      setIsRunning(false);
    }
  };

  // -------------------------------------------------------------------------
  // Derived counts for the legend bar
  // -------------------------------------------------------------------------
  const counts = React.useMemo(() => ({
    evaluate: clauses.filter((c) => clauseStates[c.id] === S.DEFAULT).length,
    limit: clauses.filter((c) => clauseStates[c.id] === S.LIMIT).length,
    ignore: clauses.filter((c) => clauseStates[c.id] === S.IGNORE).length,
  }), [clauses, clauseStates]);

  // -------------------------------------------------------------------------
  // Render
  // -------------------------------------------------------------------------
  if (showLanding) {
    return (
      <LandingPage
        onRecommendDisputeForum={() => {
          setShowLanding(false);
          // Auto-trigger document scan immediately
          setTimeout(() => handleStart(), 0);
        }}
      />
    );
  }

  return (
    <div style={{
      display: "flex", flexDirection: "column", height: "100vh",
      fontFamily: "'Segoe UI', sans-serif",
      background: "#F3F3F3",
      maxWidth: "420px",
    }}>
      {/* ── Fixed Header ─────────────────────────────────────────── */}
      <div style={{
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "12px 16px",
        background: "#FFFFFF",
        borderBottom: "1px solid #E0E0E0",
        flexShrink: 0,
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ fontSize: 20 }}>🏛️</span>
          <span style={{ fontSize: 16, fontWeight: 700, color: "#1a1a1a", letterSpacing: "0.04em" }}>FORA</span>
        </div>
        <button style={{
          background: "none", border: "none", cursor: "pointer",
          fontSize: 20, color: "#555", padding: 4, borderRadius: 6,
        }} title="Settings">⚙️</button>
      </div>

      {/* ── Stats Bar ─────────────────────────────────────────────── */}
      {started && (
        <div style={{
          display: "flex", justifyContent: "space-around", alignItems: "center",
          padding: "14px 16px",
          background: "#FFFFFF",
          borderBottom: "1px solid #E8E8E8",
          flexShrink: 0,
        }}>
          <div style={{ textAlign: "center" }}>
            <div style={{ fontSize: 22, fontWeight: 700, color: "#1a1a1a" }}>{counts.evaluate}</div>
            <div style={{ fontSize: 10, fontWeight: 600, color: "#888", letterSpacing: "0.08em", textTransform: "uppercase" }}>To Evaluate</div>
          </div>
          <div style={{ width: 1, height: 32, background: "#E8E8E8" }} />
          <div style={{ textAlign: "center" }}>
            <div style={{ fontSize: 22, fontWeight: 700, color: "#1D9E75" }}>{counts.limit}</div>
            <div style={{ fontSize: 10, fontWeight: 600, color: "#888", letterSpacing: "0.08em", textTransform: "uppercase" }}>Limited</div>
          </div>
          <div style={{ width: 1, height: 32, background: "#E8E8E8" }} />
          <div style={{ textAlign: "center" }}>
            <div style={{ fontSize: 22, fontWeight: 700, color: "#888" }}>{counts.ignore}</div>
            <div style={{ fontSize: 10, fontWeight: 600, color: "#888", letterSpacing: "0.08em", textTransform: "uppercase" }}>Ignored</div>
          </div>
        </div>
      )}

      {/* ── Scrollable Content ────────────────────────────────────── */}
      <div style={{ flex: 1, overflowY: "auto", paddingBottom: 140 }}>

        {/* Loading spinner */}
        {isRunning && (
          <div style={{ display: "flex", alignItems: "center", gap: 10, padding: "20px 16px" }}>
            <Spinner size={SpinnerSize.small} />
            <span style={{ fontSize: 13, color: "#555" }}>Scanning document…</span>
          </div>
        )}

        {/* Error message */}
        {errorMessage && (
          <MessageBar messageBarType={MessageBarType.error} isMultiline style={{ margin: "12px 16px" }}>
            {errorMessage}
          </MessageBar>
        )}

        {/* Best jurisdiction card */}
        {bestJurisdiction && !isRunning && (
          <div style={{
            display: "flex", alignItems: "center", gap: 12,
            margin: "12px 16px",
            padding: "10px 14px",
            borderRadius: 8,
            background: "linear-gradient(135deg, #EAF3DE 0%, #D6EDCA 100%)",
            border: "1px solid #b3d98e",
            boxShadow: "0 1px 4px rgba(0,0,0,0.07)",
          }}>
            <span style={{ fontSize: 22 }}>🏆</span>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: 10, fontWeight: 600, color: "#27500A", margin: 0, textTransform: "uppercase", letterSpacing: "0.06em" }}>
                Best Jurisdiction
              </p>
              <p style={{ fontSize: 16, fontWeight: 600, color: "#1a3d06", margin: 0 }}>{bestJurisdiction}</p>
            </div>
          </div>
        )}

        {/* Province Ranking */}
        {showResults && (
          <div style={{ padding: "0 16px" }}>
            <div style={{
              display: "flex", alignItems: "center", gap: 8,
              padding: "12px 0 6px",
              borderTop: "1px solid #E8E8E8",
            }}>
              <span style={{ fontSize: 14 }}>📊</span>
              <span style={{ fontSize: 11, fontWeight: 600, color: "#555", letterSpacing: "0.08em", textTransform: "uppercase" }}>Province Ranking</span>
            </div>
            <ProvinceRanking
              clauseStates={clauseStates}
              clauseText={clauseText}
              data={rankingData}
              worstData={worstData}
            />
          </div>
        )}

        {/* Clause Triage Section */}
        {started && clauses.length > 0 && (
          <div style={{ padding: "0 16px" }}>
            {/* Triage header */}
            <div style={{
              display: "flex", alignItems: "center", gap: 8,
              padding: "14px 0 8px",
            }}>
              <span style={{ fontSize: 14 }}>☑️</span>
              <span style={{ fontSize: 11, fontWeight: 600, color: "#555", letterSpacing: "0.08em", textTransform: "uppercase" }}>Clause Triage</span>
            </div>

            {/* Legend */}
            <div style={{
              display: "flex", gap: 12, marginBottom: 10, flexWrap: "wrap",
              fontSize: 11, color: "#a19f9d",
              padding: "6px 10px",
              background: "#EBEBEB",
              borderRadius: 6,
            }}>
              <span><span style={{ fontWeight: 700, color: "#A32D2D" }}>!</span> — limit enforceability</span>
              <span style={{ color: "#c8c6c4" }}>|</span>
              <span><span style={{ fontWeight: 700 }}>✕</span> — ignore clause</span>
              <span style={{ color: "#c8c6c4" }}>|</span>
              <span>Header buttons cascade to all children</span>
            </div>

            {/* Section list */}
            <div>
              {sections.map((section) => {
                const children = section.childIds.map((cid) => clauseById.get(cid)).filter(Boolean) as ClauseNode[];
                return (
                  <SectionRow
                    key={section.id}
                    node={section}
                    children={children}
                    clauseStates={clauseStates}
                    onSetState={handleSetState}
                    onCascade={handleCascade}
                    onNavigate={handleNavigate}
                  />
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* ── Fixed Bottom Action Bar ───────────────────────────────── */}
      <div style={{
        position: "fixed", bottom: 0, left: 0, right: 0, maxWidth: 420,
        background: "#FFFFFF",
        borderTop: "1px solid #E0E0E0",
        padding: "10px 16px 12px",
        zIndex: 100,
      }}>
        {/* Row 1: Start + Continue */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 8 }}>
          <button
            onClick={handleStart}
            disabled={isRunning}
            style={{
              display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
              padding: "10px 0",
              background: isRunning ? "#555" : "#1a1a1a",
              color: "#FFFFFF",
              border: "none",
              borderRadius: 6,
              fontSize: 14, fontWeight: 600,
              cursor: isRunning ? "not-allowed" : "pointer",
            }}
          >
            <span style={{ fontSize: 12 }}>▶</span> Start
          </button>
          <button
            onClick={handleContinue}
            disabled={isRunning || !started}
            style={{
              display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
              padding: "10px 0",
              background: "#FFFFFF",
              color: isRunning || !started ? "#AAA" : "#1a1a1a",
              border: `1.5px solid ${isRunning || !started ? "#DDD" : "#AAAAAA"}`,
              borderRadius: 6,
              fontSize: 14, fontWeight: 600,
              cursor: isRunning || !started ? "not-allowed" : "pointer",
            }}
          >
            <span style={{ fontSize: 12 }}>▶</span> Continue
          </button>
        </div>
        {/* Row 2: Reset / Ignore All / Limit All */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 4 }}>
          <button
            onClick={handleReset}
            disabled={isRunning}
            style={{
              background: "none", border: "none",
              fontSize: 11, fontWeight: 600,
              color: "#555",
              letterSpacing: "0.06em",
              textTransform: "uppercase",
              cursor: "pointer", padding: "4px 0",
            }}
          >Reset</button>
          <button
            onClick={handleIgnoreAll}
            disabled={isRunning}
            style={{
              background: "none", border: "none",
              fontSize: 11, fontWeight: 600,
              color: "#555",
              letterSpacing: "0.06em",
              textTransform: "uppercase",
              cursor: "pointer", padding: "4px 0",
            }}
          >Ignore All</button>
          <button
            onClick={handleLimitAll}
            disabled={isRunning}
            style={{
              background: "none", border: "none",
              fontSize: 11, fontWeight: 600,
              color: "#A32D2D",
              letterSpacing: "0.06em",
              textTransform: "uppercase",
              cursor: "pointer", padding: "4px 0",
            }}
          >Limit All</button>
        </div>
      </div>
    </div>
  );
};

export default App;